### ISSUE TITLE
linux下终端运行报错

### ISSUE THREAD

**Issue by kikyoulzg** [1u4nx/yugioh_card_query#1]
环境：
deepin20.4, python 3.7.3, pyqt 5.15.4

报错内容:
Traceback (most recent call last):
  File "/usr/bin/yugioh_card_query", line 10, in <module>
    from PyQt5 import QtCore
ImportError: /home/kikyoulzg/.local/lib/python3.7/site-packages/PyQt5/QtCore.abi3.so: symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference

如果用sudo 运行,可以打开应用但无法输入中文  (

**Comment by lu4nx** [comment]
我在 deepin 20.4 用 pip 直接安装 PyQt5 后可以正常工作：

```sudo pip3 install pyqt5```

你可以尝试非root身份卸载有冲突的PyQt5（/home/kikyoulzg/.local/lib/python3.7/site-packages/PyQt5/）后再试：

```pip3 uninstall pyqt5```

 关于无法输入中文可能和环境变量有关（可能root帐号默认没设置），可以检查是否设置了QT_IM_MODULE。例如默认使用的输入法是 fcitx5，在 ~/.profile 中增加：

export QT_IM_MODULE=fcitx

**Comment by kikyoulzg** [comment]
> 我在 deepin 20.4 用 pip 直接安装 PyQt5 后可以正常工作：
> 
> `sudo pip3 install pyqt5`
> 
> 你可以尝试非root身份卸载有冲突的PyQt5（/home/kikyoulzg/.local/lib/python3.7/site-packages/PyQt5/）后再试：
> 
> `pip3 uninstall pyqt5`
> 
> 关于无法输入中文可能和环境变量有关（可能root帐号默认没设置），可以检查是否设置了QT_IM_MODULE。例如默认使用的输入法是 fcitx5，在 ~/.profile 中增加：
> 
> export QT_IM_MODULE=fcitx

卸载普通用户的pyqt5后可以正常打开了.不过我的输入法是fcitx5,依旧无法输入中文,在托盘的键盘图标上悬停显示"无输入框".

**Comment by lu4nx** [comment]
试一试设置环境变量。

**Comment by kikyoulzg** [comment]
> 试一试设置环境变量。

sudo cp /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so /usr/local/lib/python3.7/dist-packages/PyQt5/Qt5/plugins/platforminputcontexts

环境变量设置以后,再执行上面的命令就可以正常使用了.谢谢大佬开发的工具!
