### ISSUE TITLE
搜索栏不能输入中文

### ISSUE THREAD

**Issue by patrolli** [1u4nx/yugioh_card_query#2]
您好，我成功安装了 yugioh_card_query, 但在搜索栏还是不能切换中文输入法，我的系统的 arch linux，使用 rime 输入法。

![image](https://user-images.githubusercontent.com/25717445/161414758-ba200e09-ff5b-4219-ab37-7d51e1580b34.png)

**Comment by lu4nx** [comment]
应该是输入法与Qt之间衔接的问题，可能你没配置环境变量，检查下是否设置了QT_IM_MODULE：

env | fgrep QT_IM_MODULE

如果未设置，例如默认使用的输入法是 fcitx5，在 ~/.profile 中增加：

export QT_IM_MODULE=fcitx

然后注销重新登录桌面试试。
